### ISSUE TITLE
Как отключить затемение картинок?

### ISSUE THREAD

**Issue by OmikronGamma** [BANOnotIT/HabrDarkSide#4]
Привет, как отключить затемение картинок?

**Comment by BANOnotIT** [comment]
К сожалению пока что только удалением строк из исходников

**Comment by BANOnotIT** [comment]
Нудно будет много настроек сделать, как только будет возможность сделаю небольшой фреймворк для публикации

**Comment by OmikronGamma** [comment]
> К сожалению пока что только удалением строк из исходников

Отлично, скажите каких.

**Comment by BANOnotIT** [comment]
Вообще целый селектор нужно бы удалить, то есть вот этот:
```css
.default-block__content #facebook_like_box,.default-block__content #vk_groups,.post img,.company_top_banner img,img .teaser__image,.article__body img{-webkit-filter:grayscale(1);filter:grayscale(1);opacity:.5;transition:all .6s ease-in-out}
```
Если вдруг что-то сломается (хотя я думаю вы достаточно продвинуты, раз хабр читаете ;-)), то верните всё обратно, а потом удалите только то, что находится внутри фигурных скобок `{` и `}`.
